const ACTION_TYPES = {
  TWEETS: { ADD: 'ADD', CLEAR: 'CLEAR' },
  LOADING: { START_LOADING: 'START_LOADING', STOP_LOADING: 'STOP_LOADING' },
  ERROR: { HAS_ERROR: 'HAS_ERROR' },
  MAX_TWEETS: { ADD: 'ADD_MAX_TWEETS', RESET: 'RESET_MAX_TWEETS' },
  SEARCH_TEXT: { ADD: 'ADD_SEARCH_TEXT', FIRST_RULE_ADDITION: 'FIRST_RULE_ADDITION' },
};

export default ACTION_TYPES;
